export const BRAND_COLOR = "#396AE5";

export const PLANS = [
  {
    id: "free",
    name: "무료",
    price: 0,
    description: "회고를 시작하는 분들을 위한 기본 플랜",
    features: [
      "1개의 크루 참여",
      "개인 회고 작성",
      "기본 AI 인사이트",
      "커뮤니티 피드",
      "소셜 로그인 (네이버/카카오)",
      "프로필 꾸미기",
    ],
    cta: "시작하기",
  },
  {
    id: "pro",
    name: "프로",
    price: 5000,
    description: "더 깊은 회고와 성장을 원하는 분들을 위한 플랜",
    features: [
      "무제한 크루 참여",
      "개인 회고 작성",
      "AI 기반 챌린지",
      "주간 AI 분석",
      "성장 트래킹",
      "상세 분석",
    ],
    cta: "프로로 업그레이드",
  },
  {
    id: "enterprise",
    name: "단체",
    price: 15000,
    description: "크루나 커뮤니티를 위한 단체 플랜",
    features: [
      "무제한 크루 참여",
      "개인 회고 작성",
      "고급 AI 기능",
      "성장 트래킹",
      "맞춤형 목표 설정",
      "우선 지원",
      "상세 분석",
      "SLA 보장",
      "SSO 연동",
      "API 사용",
      "맞춤 연동",
      "전담 매니저",
    ],
    cta: "문의하기",
  },
]; 